flow_planner:
  _target_: flow_planner.planner.FlowPlanner
  _convert_: "all"

  config_path: ???
  ckpt_path: ???

  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: "all"

    num_poses: 20
    time_horizon: 2

  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: "all"

    num_poses: 80
    time_horizon: 8

  device: cuda
